"""Initial migration

Revision ID: 4cba66db4e3c
Revises:
Create Date: 2023-12-22 06:01:47.740728

"""
from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision = '4cba66db4e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # users テーブルの作成
    op.create_table(
        'users',
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True),
                  primary_key=True, default=uuid.uuid4),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('nick_name', sa.String(length=30), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('gender', sa.String(length=50), nullable=True),
        sa.Column('age_range', sa.String(length=50), nullable=True),
        sa.Column('address', sa.String(length=100), nullable=True),
        sa.Column('talk_mode', sa.String(length=50), nullable=True),
        sa.Column('job_title', sa.String(length=100), nullable=True),
        sa.Column('years_of_experience', sa.String(length=50), nullable=True),
        sa.Column('firebase_uid', sa.String(length=50), nullable=True),
        sa.Column('OAuth_provider', sa.String(length=50), nullable=True),
        sa.Column('OAuth_provider_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  nullable=True, onupdate=sa.func.now()),

    )

    # llm_texts テーブルの作成
    op.create_table(
        'llm_texts',
        sa.Column('llm_text_id', sa.dialects.postgresql.UUID(as_uuid=True),
                  primary_key=True, default=uuid.uuid4),
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True),
                  sa.ForeignKey('users.user_id')),
        sa.Column('request_text', sa.Text, nullable=True),
        sa.Column('response_text', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  nullable=True, onupdate=sa.func.now()),

    )

    # payments テーブルの作成
    op.create_table(
        'payments',
        sa.Column('payment_id', sa.dialects.postgresql.UUID(as_uuid=True),
                  primary_key=True, default=uuid.uuid4),
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True),
                  sa.ForeignKey('users.user_id')),
        sa.Column('stripe_customer_id', sa.String(length=50), nullable=True),
        sa.Column('price', sa.BigInteger, nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  nullable=True, onupdate=sa.func.now()),

    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
